version: '1.0.{build}'
configuration:
  - Debug
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: false
platform: Any CPU
init:
  - ps: $Env:APPVEYOR_BUILD_NUMBER_PADDED = $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
  - appveyor-retry tools\nuget.exe restore src
  - appveyor-retry dotnet restore -v Minimal
  - ps: .\build\build.ps1 -taskList 'Validate' -configuration 'Debug' -preReleaseTag 'pr' -buildNumber $Env:APPVEYOR_BUILD_NUMBER_PADDED
build_script:
  - ps: .\build\build.ps1 -taskList 'Build' -configuration 'Debug' -preReleaseTag 'pr' -buildNumber $Env:APPVEYOR_BUILD_NUMBER_PADDED
test_script:
  - ps: .\build\build.ps1 -taskList 'Test' -configuration 'Debug' -preReleaseTag 'pr' -buildNumber $Env:APPVEYOR_BUILD_NUMBER_PADDED
artifacts:
  - path: Artifacts\Packages\*.nupkg
    name: Packages
    type: NuGetPackage
cache:
  - '%USERPROFILE%\.nuget\packages'
